import Head from "next/head";

export default function TermsAndConditions() {
  return (
    <>
      <Head>
        <title>Terms & Conditions | PSR ONE</title>
        <meta name="robots" content="noindex, follow" />
      </Head>

      <section className="py-20 bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-display font-extrabold text-gray-900 mb-8 pb-4 border-b">
            Terms & Conditions
          </h1>

          <div className="space-y-6 text-gray-650 text-sm sm:text-base leading-relaxed">
            <p className="font-bold text-slate-800">Effective Date: June 26, 2026</p>
            <p>
              By accessing this website, you agree to comply with and be bound by the following Terms and Conditions of use, which govern PSR ONE&apos;s relationship with you in relation to this website.
            </p>

            <h2 className="text-xl font-bold text-gray-900 font-heading mt-8">1. No Professional Advice Disclaimer</h2>
            <p>
              The information and calculations (including EMI and premium estimations) provided on this website are for educational and preliminary planning purposes only. They do not constitute formal financial, legal, tax, or investment advice. An official agreement and underwriting check must be executed before final terms are binding.
            </p>

            <h2 className="text-xl font-bold text-gray-900 font-heading mt-8">2. Intellectual Property</h2>
            <p>
              This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance, graphics, and codebase. Reproduction is prohibited other than in accordance with the copyright notice.
            </p>

            <h2 className="text-xl font-bold text-gray-900 font-heading mt-8">3. Limitation of Liability</h2>
            <p>
              PSR ONE shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use this website, or reliance on any calculations or projections generated by our interactive widgets.
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
